# Generated by Django 4.2.29 on 2026-04-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoría de vehículo',
                'verbose_name_plural': 'categorías de vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Ford', max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('version', models.CharField(blank=True, help_text='Ej: XLT, Titanium, Raptor.', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('kilometraje', models.PositiveIntegerField(default=0, help_text='0 para vehículos nuevos.')),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('inactivo', 'Inactivo')], default='disponible', max_length=12)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='autos.categoriavehiculo')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='autos/%Y/%m/')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar como foto de portada del vehículo.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='autos.vehiculo')),
            ],
            options={
                'verbose_name': 'imagen de vehículo',
                'verbose_name_plural': 'imágenes de vehículos',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
    ]
