# Generated by Django 4.2.29 on 2026-04-06 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autos', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora de la cita')),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=60, help_text='Duración estimada en minutos.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=12)),
                ('motivo', models.TextField(blank=True, help_text='Descripción breve de lo que el cliente desea.')),
                ('notas_vendedor', models.TextField(blank=True, help_text='Notas internas del vendedor tras la cita.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehículo de interés. Puede dejarse vacío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='autos.vehiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('vendedor', 'fecha_hora'), name='cita_unica_vendedor_fecha_hora'),
        ),
    ]
