# Generated by Django 4.2.29 on 2026-04-06 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(blank=True, help_text='Ej: SUVs, Pickups, Vehículos eléctricos.', max_length=120)),
                ('biografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='vendedores/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField()),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'disponibilidad de vendedor',
                'verbose_name_plural': 'disponibilidades de vendedores',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='disponibilidadvendedor',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='hora_fin_mayor_que_inicio'),
        ),
    ]
